const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'hight quality shirt',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 14,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 30,
      description: 'hight quality Pant',
    },
    {
      name: 'Addidas Fit Pant',
      slug: 'Addidas-Fit-Pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 65,
      countInStock: 2,
      brand: 'Addidas',
      rating: 5,
      numReviews: 4,
      description: 'hight quality Pant',
    },
    {
      name: 'Addidas Fit Shirt',
      slug: 'Addidas-Fit-Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 150,
      countInStock: 20,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 40,
      description: 'hight quality Shirt',
    },
  ],
};

export default data;
